/*
 * Typesense API
 *
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{ContentType, Error, configuration};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};

/// struct for passing parameters to the method [`create_conversation_model`]
#[derive(Clone, Debug)]
pub struct CreateConversationModelParams {
    pub conversation_model_create_schema: models::ConversationModelCreateSchema,
}

/// struct for passing parameters to the method [`delete_conversation_model`]
#[derive(Clone, Debug)]
pub struct DeleteConversationModelParams {
    /// The id of the conversation model to delete
    pub model_id: String,
}

/*
/// struct for passing parameters to the method [`retrieve_all_conversation_models`]
#[derive(Clone, Debug)]
pub struct RetrieveAllConversationModelsParams {
}
*/

/// struct for passing parameters to the method [`retrieve_conversation_model`]
#[derive(Clone, Debug)]
pub struct RetrieveConversationModelParams {
    /// The id of the conversation model to retrieve
    pub model_id: String,
}

/// struct for passing parameters to the method [`update_conversation_model`]
#[derive(Clone, Debug)]
pub struct UpdateConversationModelParams {
    /// The id of the conversation model to update
    pub model_id: String,
    pub conversation_model_update_schema: models::ConversationModelUpdateSchema,
}

/// struct for typed errors of method [`create_conversation_model`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateConversationModelError {
    Status400(models::ApiResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_conversation_model`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteConversationModelError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`retrieve_all_conversation_models`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RetrieveAllConversationModelsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`retrieve_conversation_model`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RetrieveConversationModelError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_conversation_model`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateConversationModelError {
    UnknownValue(serde_json::Value),
}

/// Create a Conversation Model
pub async fn create_conversation_model(
    configuration: &configuration::Configuration,
    params: &CreateConversationModelParams,
) -> Result<models::ConversationModelSchema, Error<CreateConversationModelError>> {
    let uri_str = format!("{}/conversations/models", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = &apikey.key;
        let value = match apikey.prefix {
            Some(ref prefix) => &format!("{prefix} {key}"),
            None => key,
        };
        req_builder = req_builder.header("X-TYPESENSE-API-KEY", value);
    };
    req_builder = req_builder.json(&params.conversation_model_create_schema);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::ConversationModelSchema`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::ConversationModelSchema`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateConversationModelError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Delete a conversation model
pub async fn delete_conversation_model(
    configuration: &configuration::Configuration,
    params: &DeleteConversationModelParams,
) -> Result<models::ConversationModelSchema, Error<DeleteConversationModelError>> {
    let uri_str = format!(
        "{}/conversations/models/{modelId}",
        configuration.base_path,
        modelId = crate::apis::urlencode(&params.model_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = &apikey.key;
        let value = match apikey.prefix {
            Some(ref prefix) => &format!("{prefix} {key}"),
            None => key,
        };
        req_builder = req_builder.header("X-TYPESENSE-API-KEY", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::ConversationModelSchema`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::ConversationModelSchema`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteConversationModelError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Retrieve all conversation models
pub async fn retrieve_all_conversation_models(
    configuration: &configuration::Configuration, /*
                                                  , params: &RetrieveAllConversationModelsParams
                                                  */
) -> Result<Vec<models::ConversationModelSchema>, Error<RetrieveAllConversationModelsError>> {
    let uri_str = format!("{}/conversations/models", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = &apikey.key;
        let value = match apikey.prefix {
            Some(ref prefix) => &format!("{prefix} {key}"),
            None => key,
        };
        req_builder = req_builder.header("X-TYPESENSE-API-KEY", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `Vec<models::ConversationModelSchema>`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `Vec<models::ConversationModelSchema>`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<RetrieveAllConversationModelsError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Retrieve a conversation model
pub async fn retrieve_conversation_model(
    configuration: &configuration::Configuration,
    params: &RetrieveConversationModelParams,
) -> Result<models::ConversationModelSchema, Error<RetrieveConversationModelError>> {
    let uri_str = format!(
        "{}/conversations/models/{modelId}",
        configuration.base_path,
        modelId = crate::apis::urlencode(&params.model_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = &apikey.key;
        let value = match apikey.prefix {
            Some(ref prefix) => &format!("{prefix} {key}"),
            None => key,
        };
        req_builder = req_builder.header("X-TYPESENSE-API-KEY", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::ConversationModelSchema`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::ConversationModelSchema`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<RetrieveConversationModelError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Update a conversation model
pub async fn update_conversation_model(
    configuration: &configuration::Configuration,
    params: &UpdateConversationModelParams,
) -> Result<models::ConversationModelSchema, Error<UpdateConversationModelError>> {
    let uri_str = format!(
        "{}/conversations/models/{modelId}",
        configuration.base_path,
        modelId = crate::apis::urlencode(&params.model_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = &apikey.key;
        let value = match apikey.prefix {
            Some(ref prefix) => &format!("{prefix} {key}"),
            None => key,
        };
        req_builder = req_builder.header("X-TYPESENSE-API-KEY", value);
    };
    req_builder = req_builder.json(&params.conversation_model_update_schema);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::ConversationModelSchema`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::ConversationModelSchema`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdateConversationModelError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
