/*
 * Typesense API
 *
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{ContentType, Error, configuration};
use crate::{apis::ResponseContent, models};
use ::std::{borrow::Cow, marker::PhantomData};
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};

/// struct for passing parameters to the method [`create_nl_search_model`]
#[derive(Clone, Debug)]
pub struct CreateNlSearchModelParams<'p> {
    /// The NL search model to be created
    pub nl_search_model_create_schema: models::NlSearchModelCreateSchema<'p>,
    pub _phantom: PhantomData<&'p ()>,
}

/// struct for passing parameters to the method [`delete_nl_search_model`]
#[derive(Clone, Debug)]
pub struct DeleteNlSearchModelParams<'p> {
    /// The ID of the NL search model to delete
    pub model_id: Cow<'p, str>,
    pub _phantom: PhantomData<&'p ()>,
}

/// struct for passing parameters to the method [`retrieve_nl_search_model`]
#[derive(Clone, Debug)]
pub struct RetrieveNlSearchModelParams<'p> {
    /// The ID of the NL search model to retrieve
    pub model_id: Cow<'p, str>,
    pub _phantom: PhantomData<&'p ()>,
}

/// struct for passing parameters to the method [`update_nl_search_model`]
#[derive(Clone, Debug)]
pub struct UpdateNlSearchModelParams<'p> {
    /// The ID of the NL search model to update
    pub model_id: Cow<'p, str>,
    /// The NL search model fields to update
    pub body: models::NlSearchModelCreateSchema<'p>,
    pub _phantom: PhantomData<&'p ()>,
}

/// struct for typed errors of method [`create_nl_search_model`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateNlSearchModelError {
    Status400(models::ApiResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_nl_search_model`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteNlSearchModelError {
    Status404(models::ApiResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`retrieve_all_nl_search_models`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RetrieveAllNlSearchModelsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`retrieve_nl_search_model`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RetrieveNlSearchModelError {
    Status404(models::ApiResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_nl_search_model`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateNlSearchModelError {
    Status400(models::ApiResponse),
    Status404(models::ApiResponse),
    UnknownValue(serde_json::Value),
}

/// Create a new NL search model.
pub async fn create_nl_search_model(
    configuration: &configuration::Configuration,
    params: &CreateNlSearchModelParams<'_>,
) -> Result<models::NlSearchModelSchema, Error<CreateNlSearchModelError>> {
    let uri_str = format!("{}/nl_search_models", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = &apikey.key;
        let value = match apikey.prefix {
            Some(ref prefix) => &format!("{prefix} {key}"),
            None => key,
        };
        req_builder = req_builder.header("X-TYPESENSE-API-KEY", value);
    };
    req_builder = req_builder.json(&params.nl_search_model_create_schema);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::NlSearchModelSchema`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::NlSearchModelSchema`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateNlSearchModelError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Delete a specific NL search model by its ID.
pub async fn delete_nl_search_model(
    configuration: &configuration::Configuration,
    params: &DeleteNlSearchModelParams<'_>,
) -> Result<models::NlSearchModelDeleteSchema, Error<DeleteNlSearchModelError>> {
    let uri_str = format!(
        "{}/nl_search_models/{modelId}",
        configuration.base_path,
        modelId = crate::apis::urlencode(&params.model_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = &apikey.key;
        let value = match apikey.prefix {
            Some(ref prefix) => &format!("{prefix} {key}"),
            None => key,
        };
        req_builder = req_builder.header("X-TYPESENSE-API-KEY", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::NlSearchModelDeleteSchema`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::NlSearchModelDeleteSchema`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteNlSearchModelError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Retrieve all NL search models.
pub async fn retrieve_all_nl_search_models(
    configuration: &configuration::Configuration,
) -> Result<Vec<models::NlSearchModelSchema>, Error<RetrieveAllNlSearchModelsError>> {
    let uri_str = format!("{}/nl_search_models", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = &apikey.key;
        let value = match apikey.prefix {
            Some(ref prefix) => &format!("{prefix} {key}"),
            None => key,
        };
        req_builder = req_builder.header("X-TYPESENSE-API-KEY", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `Vec<models::NlSearchModelSchema>`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `Vec<models::NlSearchModelSchema>`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<RetrieveAllNlSearchModelsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Retrieve a specific NL search model by its ID.
pub async fn retrieve_nl_search_model(
    configuration: &configuration::Configuration,
    params: &RetrieveNlSearchModelParams<'_>,
) -> Result<models::NlSearchModelSchema, Error<RetrieveNlSearchModelError>> {
    let uri_str = format!(
        "{}/nl_search_models/{modelId}",
        configuration.base_path,
        modelId = crate::apis::urlencode(&params.model_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = &apikey.key;
        let value = match apikey.prefix {
            Some(ref prefix) => &format!("{prefix} {key}"),
            None => key,
        };
        req_builder = req_builder.header("X-TYPESENSE-API-KEY", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::NlSearchModelSchema`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::NlSearchModelSchema`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<RetrieveNlSearchModelError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Update an existing NL search model.
pub async fn update_nl_search_model(
    configuration: &configuration::Configuration,
    params: &UpdateNlSearchModelParams<'_>,
) -> Result<models::NlSearchModelSchema, Error<UpdateNlSearchModelError>> {
    let uri_str = format!(
        "{}/nl_search_models/{modelId}",
        configuration.base_path,
        modelId = crate::apis::urlencode(&params.model_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = &apikey.key;
        let value = match apikey.prefix {
            Some(ref prefix) => &format!("{prefix} {key}"),
            None => key,
        };
        req_builder = req_builder.header("X-TYPESENSE-API-KEY", value);
    };
    req_builder = req_builder.json(&params.body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::NlSearchModelSchema`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::NlSearchModelSchema`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdateNlSearchModelError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
