/*
 * Typesense API
 *
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{ContentType, Error, configuration};
use crate::{apis::ResponseContent, models};
use ::std::{borrow::Cow, marker::PhantomData};
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};

/// struct for passing parameters to the method [`delete_stopwords_set`]
#[derive(Clone, Debug)]
pub struct DeleteStopwordsSetParams<'p> {
    /// The ID of the stopwords set to delete.
    pub set_id: Cow<'p, str>,
    pub _phantom: PhantomData<&'p ()>,
}

/// struct for passing parameters to the method [`retrieve_stopwords_set`]
#[derive(Clone, Debug)]
pub struct RetrieveStopwordsSetParams<'p> {
    /// The ID of the stopwords set to retrieve.
    pub set_id: Cow<'p, str>,
    pub _phantom: PhantomData<&'p ()>,
}

/// struct for passing parameters to the method [`upsert_stopwords_set`]
#[derive(Clone, Debug)]
pub struct UpsertStopwordsSetParams<'p> {
    /// The ID of the stopwords set to upsert.
    pub set_id: Cow<'p, str>,
    /// The stopwords set to upsert.
    pub stopwords_set_upsert_schema: models::StopwordsSetUpsertSchema<'p>,
    pub _phantom: PhantomData<&'p ()>,
}

/// struct for typed errors of method [`delete_stopwords_set`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteStopwordsSetError<'a> {
    Status404(models::ApiResponse<'a>),
    UnknownValue {
        value: serde_json::Value,
        #[serde(skip)]
        _phantom: PhantomData<&'a ()>,
    },
}

/// struct for typed errors of method [`retrieve_stopwords_set`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RetrieveStopwordsSetError<'a> {
    Status404(models::ApiResponse<'a>),
    UnknownValue {
        value: serde_json::Value,
        #[serde(skip)]
        _phantom: PhantomData<&'a ()>,
    },
}

/// struct for typed errors of method [`retrieve_stopwords_sets`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RetrieveStopwordsSetsError<'a> {
    UnknownValue {
        value: serde_json::Value,
        #[serde(skip)]
        _phantom: PhantomData<&'a ()>,
    },
}

/// struct for typed errors of method [`upsert_stopwords_set`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpsertStopwordsSetError<'a> {
    Status400(models::ApiResponse<'a>),
    UnknownValue {
        value: serde_json::Value,
        #[serde(skip)]
        _phantom: PhantomData<&'a ()>,
    },
}

/// Permanently deletes a stopwords set, given it's name.
pub async fn delete_stopwords_set(
    configuration: &configuration::Configuration,
    params: &DeleteStopwordsSetParams<'_>,
) -> Result<models::DeleteStopwordsSet200Response<'static>, Error<DeleteStopwordsSetError<'static>>>
{
    let uri_str = format!(
        "{}/stopwords/{setId}",
        configuration.base_path,
        setId = crate::apis::urlencode(&params.set_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = &apikey.key;
        let value = match apikey.prefix {
            Some(ref prefix) => &format!("{prefix} {key}"),
            None => key,
        };
        req_builder = req_builder.header("X-TYPESENSE-API-KEY", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::DeleteStopwordsSet200Response`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::DeleteStopwordsSet200Response`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteStopwordsSetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Retrieve the details of a stopwords set, given it's name.
pub async fn retrieve_stopwords_set(
    configuration: &configuration::Configuration,
    params: &RetrieveStopwordsSetParams<'_>,
) -> Result<models::StopwordsSetRetrieveSchema<'static>, Error<RetrieveStopwordsSetError<'static>>>
{
    let uri_str = format!(
        "{}/stopwords/{setId}",
        configuration.base_path,
        setId = crate::apis::urlencode(&params.set_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = &apikey.key;
        let value = match apikey.prefix {
            Some(ref prefix) => &format!("{prefix} {key}"),
            None => key,
        };
        req_builder = req_builder.header("X-TYPESENSE-API-KEY", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::StopwordsSetRetrieveSchema`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::StopwordsSetRetrieveSchema`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<RetrieveStopwordsSetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Retrieve the details of all stopwords sets
pub async fn retrieve_stopwords_sets(
    configuration: &configuration::Configuration,
) -> Result<
    models::StopwordsSetsRetrieveAllSchema<'static>,
    Error<RetrieveStopwordsSetsError<'static>>,
> {
    let uri_str = format!("{}/stopwords", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = &apikey.key;
        let value = match apikey.prefix {
            Some(ref prefix) => &format!("{prefix} {key}"),
            None => key,
        };
        req_builder = req_builder.header("X-TYPESENSE-API-KEY", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::StopwordsSetsRetrieveAllSchema`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::StopwordsSetsRetrieveAllSchema`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<RetrieveStopwordsSetsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// When an analytics rule is created, we give it a name and describe the type, the source collections and the destination collection.
pub async fn upsert_stopwords_set(
    configuration: &configuration::Configuration,
    params: &UpsertStopwordsSetParams<'_>,
) -> Result<models::StopwordsSetSchema<'static>, Error<UpsertStopwordsSetError<'static>>> {
    let uri_str = format!(
        "{}/stopwords/{setId}",
        configuration.base_path,
        setId = crate::apis::urlencode(&params.set_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = &apikey.key;
        let value = match apikey.prefix {
            Some(ref prefix) => &format!("{prefix} {key}"),
            None => key,
        };
        req_builder = req_builder.header("X-TYPESENSE-API-KEY", value);
    };
    req_builder = req_builder.json(&params.stopwords_set_upsert_schema);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => {
                return Err(Error::from(serde_json::Error::custom(
                    "Received `text/plain` content type response that cannot be converted to `models::StopwordsSetSchema`",
                )));
            }
            ContentType::Unsupported(unknown_type) => {
                return Err(Error::from(serde_json::Error::custom(format!(
                    "Received `{unknown_type}` content type response that cannot be converted to `models::StopwordsSetSchema`"
                ))));
            }
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UpsertStopwordsSetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
