/*
 * Typesense API
 *
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use ::std::borrow::Cow;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalyticsRuleCreate<'a> {
    #[serde(rename = "name")]
    pub name: Cow<'a, str>,
    #[serde(rename = "type")]
    pub r#type: models::AnalyticsRuleType,
    #[serde(rename = "collection")]
    pub collection: Cow<'a, str>,
    #[serde(rename = "event_type")]
    pub event_type: Cow<'a, str>,
    #[serde(rename = "rule_tag", skip_serializing_if = "Option::is_none")]
    pub rule_tag: Option<Cow<'a, str>>,
    #[serde(rename = "params", skip_serializing_if = "Option::is_none")]
    pub params: Option<Box<models::AnalyticsRuleCreateParams<'a>>>,
}

impl<'a> AnalyticsRuleCreate<'a> {
    pub fn new(
        name: Cow<'a, str>,
        r#type: models::AnalyticsRuleType,
        collection: Cow<'a, str>,
        event_type: Cow<'a, str>,
    ) -> Self {
        Self {
            name,
            r#type,
            collection,
            event_type,
            rule_tag: None,
            params: None,
        }
    }
}
