/*
 * Typesense API
 *
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use ::std::{borrow::Cow, marker::PhantomData};
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalyticsEventsResponse<'a> {
    #[serde(rename = "events")]
    pub events: Vec<models::AnalyticsEventsResponseEventsInner<'a>>,
    #[serde(skip)]
    pub _phantom: PhantomData<&'a ()>,
}

impl<'a> AnalyticsEventsResponse<'a> {
    pub fn new(events: Vec<models::AnalyticsEventsResponseEventsInner<'a>>) -> Self {
        Self {
            events,
            _phantom: PhantomData,
        }
    }
}
