/*
 * Typesense API
 *
 * An open source search engine for building delightful search experiences.
 * The version of the OpenAPI document: 30.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalyticsEventCreateResponse {
    #[serde(rename = "ok")]
    pub ok: bool,
}

impl AnalyticsEventCreateResponse {
    pub fn new(ok: bool) -> AnalyticsEventCreateResponse {
        AnalyticsEventCreateResponse { ok }
    }
}
