/*
 * Typesense API
 *
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 0.25.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalyticsRuleSchema {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "params")]
    pub params: Box<crate::models::AnalyticsRuleParameters>,
}

impl AnalyticsRuleSchema {
    pub fn new(
        name: String,
        r#type: String,
        params: crate::models::AnalyticsRuleParameters,
    ) -> AnalyticsRuleSchema {
        AnalyticsRuleSchema {
            name,
            r#type,
            params: Box::new(params),
        }
    }
}
