/*
 * Typesense API
 *
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 28.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalyticsRuleParametersDestination {
    #[serde(rename = "collection")]
    pub collection: String,
    #[serde(rename = "counter_field", skip_serializing_if = "Option::is_none")]
    pub counter_field: Option<String>,
}

impl AnalyticsRuleParametersDestination {
    pub fn new(collection: String) -> AnalyticsRuleParametersDestination {
        AnalyticsRuleParametersDestination {
            collection,
            counter_field: None,
        }
    }
}

