/*
 * Typesense API
 *
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalyticsEventsResponse {
    #[serde(rename = "events")]
    pub events: Vec<models::AnalyticsEventsResponseEventsInner>,
}

impl AnalyticsEventsResponse {
    pub fn new(events: Vec<models::AnalyticsEventsResponseEventsInner>) -> AnalyticsEventsResponse{
        AnalyticsEventsResponse {
            events,
        }
    }
}

