/*
 * Typesense API
 *
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use ::std::{borrow::Cow, marker::PhantomData};
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalyticsRuleCreateParams<'a> {
    #[serde(
        rename = "destination_collection",
        skip_serializing_if = "Option::is_none"
    )]
    pub destination_collection: Option<Cow<'a, str>>,
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i32>,
    #[serde(
        rename = "capture_search_requests",
        skip_serializing_if = "Option::is_none"
    )]
    pub capture_search_requests: Option<bool>,
    #[serde(rename = "meta_fields", skip_serializing_if = "Option::is_none")]
    pub meta_fields: Option<Vec<String>>,
    #[serde(rename = "expand_query", skip_serializing_if = "Option::is_none")]
    pub expand_query: Option<bool>,
    #[serde(rename = "counter_field", skip_serializing_if = "Option::is_none")]
    pub counter_field: Option<Cow<'a, str>>,
    #[serde(rename = "weight", skip_serializing_if = "Option::is_none")]
    pub weight: Option<i32>,
    #[serde(skip)]
    pub _phantom: PhantomData<&'a ()>,
}

impl<'a> AnalyticsRuleCreateParams<'a> {
    pub fn new() -> Self {
        Self {
            destination_collection: None,
            limit: None,
            capture_search_requests: None,
            meta_fields: None,
            expand_query: None,
            counter_field: None,
            weight: None,
            _phantom: PhantomData,
        }
    }
}
