/*
 * Typesense API
 *
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 0.25.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalyticsRuleParametersSource {
    #[serde(rename = "collections", skip_serializing_if = "Option::is_none")]
    pub collections: Option<Vec<String>>,
}

impl AnalyticsRuleParametersSource {
    pub fn new() -> AnalyticsRuleParametersSource {
        AnalyticsRuleParametersSource { collections: None }
    }
}
