/*
 * Typesense API
 *
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 28.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalyticsEventCreateSchema {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "data")]
    pub data: serde_json::Value,
}

impl AnalyticsEventCreateSchema {
    pub fn new(r#type: String, name: String, data: serde_json::Value) -> AnalyticsEventCreateSchema {
        AnalyticsEventCreateSchema {
            r#type,
            name,
            data,
        }
    }
}

