/*
 * Typesense API
 *
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use ::std::borrow::Cow;
use serde::{Deserialize, Serialize};

/// AnalyticsEventData : Event payload
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalyticsEventData<'a> {
    #[serde(rename = "user_id", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<Cow<'a, str>>,
    #[serde(rename = "doc_id", skip_serializing_if = "Option::is_none")]
    pub doc_id: Option<Cow<'a, str>>,
    #[serde(rename = "doc_ids", skip_serializing_if = "Option::is_none")]
    pub doc_ids: Option<Vec<String>>,
    #[serde(rename = "q", skip_serializing_if = "Option::is_none")]
    pub q: Option<Cow<'a, str>>,
    #[serde(rename = "analytics_tag", skip_serializing_if = "Option::is_none")]
    pub analytics_tag: Option<Cow<'a, str>>,
}

impl<'a> AnalyticsEventData<'a> {
    /// Event payload
    pub fn new() -> Self {
        Self {
            user_id: None,
            doc_id: None,
            doc_ids: None,
            q: None,
            analytics_tag: None,
        }
    }
}
