/*
 * Typesense API
 *
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use ::std::{borrow::Cow, marker::PhantomData};
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiKey<'a> {
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<Cow<'a, str>>,
    #[serde(rename = "description")]
    pub description: Cow<'a, str>,
    #[serde(rename = "actions")]
    pub actions: Vec<String>,
    #[serde(rename = "collections")]
    pub collections: Vec<String>,
    #[serde(rename = "expires_at", skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<i64>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    #[serde(rename = "value_prefix", skip_serializing_if = "Option::is_none")]
    pub value_prefix: Option<Cow<'a, str>>,
    #[serde(skip)]
    pub _phantom: PhantomData<&'a ()>,
}

impl<'a> ApiKey<'a> {
    pub fn new(description: Cow<'a, str>, actions: Vec<String>, collections: Vec<String>) -> Self {
        Self {
            value: None,
            description,
            actions,
            collections,
            expires_at: None,
            id: None,
            value_prefix: None,
            _phantom: PhantomData,
        }
    }
}
