/*
 * Typesense API
 *
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 0.23.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct ApiResponse {
    #[serde(rename = "message")]
    pub message: String,
}

impl ApiResponse {
    pub fn new(message: String) -> ApiResponse {
        ApiResponse { message }
    }
}
