/*
 * Typesense API
 *
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use ::std::{borrow::Cow, marker::PhantomData};
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiKeysResponse<'a> {
    #[serde(rename = "keys")]
    pub keys: Vec<models::ApiKey<'a>>,
    #[serde(skip)]
    pub _phantom: PhantomData<&'a ()>,
}

impl<'a> ApiKeysResponse<'a> {
    pub fn new(keys: Vec<models::ApiKey<'a>>) -> Self {
        Self {
            keys,
            _phantom: PhantomData,
        }
    }
}
