/*
 * Typesense API
 *
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct ApiKeyDeleteResponse {
    /// The id of the API key that was deleted
    #[serde(rename = "id")]
    pub id: i64,
}

impl ApiKeyDeleteResponse {
    pub fn new(id: i64) -> ApiKeyDeleteResponse{
        ApiKeyDeleteResponse {
            id,
        }
    }
}

