/*
 * Typesense API
 *
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 0.23.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct ApiKeyAllOf {
    #[serde(rename = "id")]
    pub id: i64,
    #[serde(rename = "value")]
    pub value: String,
    #[serde(rename = "value_prefix")]
    pub value_prefix: String,
}

impl ApiKeyAllOf {
    pub fn new(id: i64, value: String, value_prefix: String) -> ApiKeyAllOf {
        ApiKeyAllOf {
            id,
            value,
            value_prefix,
        }
    }
}
