/*
 * Typesense API
 *
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use ::std::{borrow::Cow, marker::PhantomData};
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CollectionAliasSchema<'a> {
    /// Name of the collection you wish to map the alias to
    #[serde(rename = "collection_name")]
    pub collection_name: Cow<'a, str>,
    #[serde(skip)]
    pub _phantom: PhantomData<&'a ()>,
}

impl<'a> CollectionAliasSchema<'a> {
    pub fn new(collection_name: Cow<'a, str>) -> Self {
        Self {
            collection_name,
            _phantom: PhantomData,
        }
    }
}
