/*
 * Typesense API
 *
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 0.23.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct CollectionAliasSchema {
    /// Name of the collection you wish to map the alias to
    #[serde(rename = "collection_name")]
    pub collection_name: String,
}

impl CollectionAliasSchema {
    pub fn new(collection_name: String) -> CollectionAliasSchema {
        CollectionAliasSchema { collection_name }
    }
}
