/*
 * Typesense API
 *
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 0.23.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct CollectionAliasesResponse {
    #[serde(rename = "aliases")]
    pub aliases: Vec<crate::models::CollectionAlias>,
}

impl CollectionAliasesResponse {
    pub fn new(aliases: Vec<crate::models::CollectionAlias>) -> CollectionAliasesResponse {
        CollectionAliasesResponse { aliases }
    }
}
