/*
 * Typesense API
 *
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
#[builder(on(String, into))]
pub struct CollectionAliasesResponse {
    #[serde(rename = "aliases")]
    pub aliases: Vec<models::CollectionAlias>,
}

impl CollectionAliasesResponse {
    pub fn new(aliases: Vec<models::CollectionAlias>) -> CollectionAliasesResponse{
        CollectionAliasesResponse {
            aliases,
        }
    }
}

