/*
 * Typesense API
 *
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use ::std::{borrow::Cow, marker::PhantomData};
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CollectionAliasesResponse<'a> {
    #[serde(rename = "aliases")]
    pub aliases: Vec<models::CollectionAlias<'a>>,
    #[serde(skip)]
    pub _phantom: PhantomData<&'a ()>,
}

impl<'a> CollectionAliasesResponse<'a> {
    pub fn new(aliases: Vec<models::CollectionAlias<'a>>) -> Self {
        Self {
            aliases,
            _phantom: PhantomData,
        }
    }
}
