/*
 * Typesense API
 *
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use ::std::borrow::Cow;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateAnalyticsRuleRequest<'a> {
    AnalyticsRuleCreate(Box<models::AnalyticsRuleCreate<'a>>),
    Array(Vec<models::AnalyticsRuleCreate<'a>>),
}

impl Default for CreateAnalyticsRuleRequest<'_> {
    fn default() -> Self {
        Self::AnalyticsRuleCreate(Default::default())
    }
}
