/*
 * Typesense API
 *
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use ::std::{borrow::Cow, marker::PhantomData};
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CurationInclude<'a> {
    /// document id that should be included
    #[serde(rename = "id")]
    pub id: String,
    /// position number where document should be included in the search results
    #[serde(rename = "position")]
    pub position: i32,
    #[serde(skip)]
    pub _phantom: PhantomData<&'a ()>,
}

impl<'a> CurationInclude<'a> {
    pub fn new(id: String, position: i32) -> Self {
        Self {
            id,
            position,
            _phantom: PhantomData,
        }
    }
}
