/*
 * Typesense API
 *
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use ::std::{borrow::Cow, marker::PhantomData};
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CurationExclude<'a> {
    /// document id that should be excluded from the search results.
    #[serde(rename = "id")]
    pub id: Cow<'a, str>,
    #[serde(skip)]
    pub _phantom: PhantomData<&'a ()>,
}

impl<'a> CurationExclude<'a> {
    pub fn new(id: Cow<'a, str>) -> Self {
        Self {
            id,
            _phantom: PhantomData,
        }
    }
}
