/*
 * Typesense API
 *
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use ::std::borrow::Cow;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteStopwordsSet200Response {
    #[serde(rename = "id")]
    pub id: String,
}

impl DeleteStopwordsSet200Response {
    pub fn new(id: String) -> Self {
        Self { id }
    }
}
