/*
 * Typesense API
 *
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 0.23.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct DeleteDocumentsDeleteDocumentsParametersParameter {
    #[serde(rename = "filter_by", skip_serializing_if = "Option::is_none")]
    pub filter_by: Option<String>,
    /// Batch size parameter controls the number of documents that should be deleted at a time. A larger value will speed up deletions, but will impact performance of other operations running on the server.
    #[serde(rename = "batch_size", skip_serializing_if = "Option::is_none")]
    pub batch_size: Option<i32>,
}

impl DeleteDocumentsDeleteDocumentsParametersParameter {
    pub fn new() -> DeleteDocumentsDeleteDocumentsParametersParameter {
        DeleteDocumentsDeleteDocumentsParametersParameter {
            filter_by: None,
            batch_size: None,
        }
    }
}
