/*
 * Typesense API
 *
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use ::std::{borrow::Cow, marker::PhantomData};
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteDocuments200Response<'a> {
    #[serde(rename = "num_deleted")]
    pub num_deleted: i32,
    #[serde(skip)]
    pub _phantom: PhantomData<&'a ()>,
}

impl<'a> DeleteDocuments200Response<'a> {
    pub fn new(num_deleted: i32) -> Self {
        Self {
            num_deleted,
            _phantom: PhantomData,
        }
    }
}
