/*
 * Typesense API
 *
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 28.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DocumentIndexParameters {
    #[serde(rename = "dirty_values", skip_serializing_if = "Option::is_none")]
    pub dirty_values: Option<models::DirtyValues>,
}

impl DocumentIndexParameters {
    pub fn new() -> DocumentIndexParameters {
        DocumentIndexParameters {
            dirty_values: None,
        }
    }
}

