/*
 * Typesense API
 *
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
#[builder(on(String, into))]
pub struct ListStemmingDictionaries200Response {
    #[serde(rename = "dictionaries", skip_serializing_if = "Option::is_none")]
    pub dictionaries: Option<Vec<String>>,
}

impl ListStemmingDictionaries200Response {
    pub fn new() -> ListStemmingDictionaries200Response{
        ListStemmingDictionaries200Response {
            dictionaries: None,
        }
    }
}

