/*
 * Typesense API
 *
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 0.23.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct MultiSearchSearchesParameter {
    #[serde(rename = "searches")]
    pub searches: Vec<crate::models::MultiSearchCollectionParameters>,
}

impl MultiSearchSearchesParameter {
    pub fn new(
        searches: Vec<crate::models::MultiSearchCollectionParameters>,
    ) -> MultiSearchSearchesParameter {
        MultiSearchSearchesParameter { searches }
    }
}
