/*
 * Typesense API
 *
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NlSearchModelDeleteSchema {
    /// ID of the deleted NL search model
    #[serde(rename = "id")]
    pub id: String,
}

impl NlSearchModelDeleteSchema {
    pub fn new(id: String) -> NlSearchModelDeleteSchema {
        NlSearchModelDeleteSchema { id }
    }
}
