/*
 * Typesense API
 *
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use ::std::{borrow::Cow, marker::PhantomData};
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PresetsRetrieveSchema<'a> {
    #[serde(rename = "presets")]
    pub presets: Vec<models::PresetSchema<'a>>,
    #[serde(skip)]
    pub _phantom: PhantomData<&'a ()>,
}

impl<'a> PresetsRetrieveSchema<'a> {
    pub fn new(presets: Vec<models::PresetSchema<'a>>) -> Self {
        Self {
            presets,
            _phantom: PhantomData,
        }
    }
}
