/*
 * Typesense API
 *
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use ::std::borrow::Cow;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PresetUpsertSchemaValue<'a> {
    SearchParameters(Box<models::SearchParameters<'a>>),
    MultiSearchSearchesParameter(Box<models::MultiSearchSearchesParameter<'a>>),
}

impl Default for PresetUpsertSchemaValue<'_> {
    fn default() -> Self {
        Self::SearchParameters(Default::default())
    }
}
