/*
 * Typesense API
 *
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use ::std::borrow::Cow;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PresetUpsertSchema<'a> {
    #[serde(rename = "value")]
    pub value: Box<models::PresetUpsertSchemaValue<'a>>,
}

impl<'a> PresetUpsertSchema<'a> {
    pub fn new(value: models::PresetUpsertSchemaValue<'a>) -> Self {
        Self {
            value: Box::new(value),
        }
    }
}
