/*
 * Typesense API
 *
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use ::std::{borrow::Cow, marker::PhantomData};
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PresetSchema<'a> {
    #[serde(rename = "value")]
    pub value: Box<models::PresetUpsertSchemaValue<'a>>,
    #[serde(rename = "name")]
    pub name: Cow<'a, str>,
    #[serde(skip)]
    pub _phantom: PhantomData<&'a ()>,
}

impl<'a> PresetSchema<'a> {
    pub fn new(value: models::PresetUpsertSchemaValue<'a>, name: Cow<'a, str>) -> Self {
        Self {
            value: Box::new(value),
            name,
            _phantom: PhantomData,
        }
    }
}
