/*
 * Typesense API
 *
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct PresetDeleteSchema {
    #[serde(rename = "name")]
    pub name: String,
}

impl PresetDeleteSchema {
    pub fn new(name: String) -> PresetDeleteSchema{
        PresetDeleteSchema {
            name,
        }
    }
}

