/*
 * Typesense API
 *
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 0.23.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct SearchOverrideExclude {
    /// document id that should be excluded from the search results.
    #[serde(rename = "id")]
    pub id: String,
}

impl SearchOverrideExclude {
    pub fn new(id: String) -> SearchOverrideExclude {
        SearchOverrideExclude { id }
    }
}
