/*
 * Typesense API
 *
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
#[builder(on(String, into))]
pub struct SearchOverrideDeleteResponse {
    /// The id of the override that was deleted
    #[serde(rename = "id")]
    pub id: String,
}

impl SearchOverrideDeleteResponse {
    pub fn new(id: String) -> SearchOverrideDeleteResponse{
        SearchOverrideDeleteResponse {
            id,
        }
    }
}

