/*
 * Typesense API
 *
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use ::std::borrow::Cow;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchSynonymsResponse {
    #[serde(rename = "synonyms")]
    pub synonyms: Vec<models::SearchSynonym>,
}

impl SearchSynonymsResponse {
    pub fn new(synonyms: Vec<models::SearchSynonym>) -> Self {
        Self { synonyms }
    }
}
