/*
 * Typesense API
 *
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
pub struct SearchSynonymDeleteResponse {
    /// The id of the synonym that was deleted
    #[serde(rename = "id")]
    pub id: String,
}

impl SearchSynonymDeleteResponse {
    pub fn new(id: String) -> SearchSynonymDeleteResponse{
        SearchSynonymDeleteResponse {
            id,
        }
    }
}

