/*
 * Typesense API
 *
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use ::std::borrow::Cow;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StemmingDictionaryWordsInner {
    /// The word form to be stemmed
    #[serde(rename = "word")]
    pub word: String,
    /// The root form of the word
    #[serde(rename = "root")]
    pub root: String,
}

impl StemmingDictionaryWordsInner {
    pub fn new(word: String, root: String) -> Self {
        Self { word, root }
    }
}
