/*
 * Typesense API
 *
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use ::std::{borrow::Cow, marker::PhantomData};
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StemmingDictionaryWordsInner<'a> {
    /// The word form to be stemmed
    #[serde(rename = "word")]
    pub word: Cow<'a, str>,
    /// The root form of the word
    #[serde(rename = "root")]
    pub root: Cow<'a, str>,
    #[serde(skip)]
    pub _phantom: PhantomData<&'a ()>,
}

impl<'a> StemmingDictionaryWordsInner<'a> {
    pub fn new(word: Cow<'a, str>, root: Cow<'a, str>) -> Self {
        Self {
            word,
            root,
            _phantom: PhantomData,
        }
    }
}
