/*
 * Typesense API
 *
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StopwordsSetsRetrieveAllSchema {
    #[serde(rename = "stopwords")]
    pub stopwords: Vec<models::StopwordsSetSchema>,
}

impl StopwordsSetsRetrieveAllSchema {
    pub fn new(stopwords: Vec<models::StopwordsSetSchema>) -> StopwordsSetsRetrieveAllSchema {
        StopwordsSetsRetrieveAllSchema {
            stopwords,
        }
    }
}

