/*
 * Typesense API
 *
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use ::std::{borrow::Cow, marker::PhantomData};
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SuccessStatus<'a> {
    #[serde(rename = "success")]
    pub success: bool,
    #[serde(skip)]
    pub _phantom: PhantomData<&'a ()>,
}

impl<'a> SuccessStatus<'a> {
    pub fn new(success: bool) -> Self {
        Self {
            success,
            _phantom: PhantomData,
        }
    }
}
