/*
 * Typesense API
 *
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SuccessStatus {
    #[serde(rename = "success")]
    pub success: bool,
}

impl SuccessStatus {
    pub fn new(success: bool) -> SuccessStatus {
        SuccessStatus {
            success,
        }
    }
}

