/*
 * Typesense API
 *
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 0.23.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct SuccessStatus {
    #[serde(rename = "success")]
    pub success: bool,
}

impl SuccessStatus {
    pub fn new(success: bool) -> SuccessStatus {
        SuccessStatus { success }
    }
}
