/*
 * Typesense API
 *
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use ::std::{borrow::Cow, marker::PhantomData};
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SynonymSetsRetrieveSchema<'a> {
    /// Array of synonym sets
    #[serde(rename = "synonym_sets")]
    pub synonym_sets: Vec<models::SynonymSetSchema<'a>>,
    #[serde(skip)]
    pub _phantom: PhantomData<&'a ()>,
}

impl<'a> SynonymSetsRetrieveSchema<'a> {
    pub fn new(synonym_sets: Vec<models::SynonymSetSchema<'a>>) -> Self {
        Self {
            synonym_sets,
            _phantom: PhantomData,
        }
    }
}
