/*
 * Typesense API
 *
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use ::std::borrow::Cow;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SynonymItemDeleteSchema {
    /// ID of the deleted synonym item
    #[serde(rename = "id")]
    pub id: String,
}

impl SynonymItemDeleteSchema {
    pub fn new(id: String) -> Self {
        Self { id }
    }
}
