/*
 * Typesense API
 *
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use ::std::{borrow::Cow, marker::PhantomData};
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SynonymSetSchema<'a> {
    /// Array of synonym items
    #[serde(rename = "items")]
    pub items: Vec<models::SynonymItemSchema<'a>>,
    /// Name of the synonym set
    #[serde(rename = "name")]
    pub name: String,
    #[serde(skip)]
    pub _phantom: PhantomData<&'a ()>,
}

impl<'a> SynonymSetSchema<'a> {
    pub fn new(items: Vec<models::SynonymItemSchema<'a>>, name: String) -> Self {
        Self {
            items,
            name,
            _phantom: PhantomData,
        }
    }
}
