/*
 * Typesense API
 *
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SynonymSetDeleteSchema {
    /// Name of the deleted synonym set
    #[serde(rename = "name")]
    pub name: String,
}

impl SynonymSetDeleteSchema {
    pub fn new(name: String) -> SynonymSetDeleteSchema{
        SynonymSetDeleteSchema {
            name,
        }
    }
}

