/*
 * Typesense API
 *
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use ::std::{borrow::Cow, marker::PhantomData};
use serde::{Deserialize, Serialize};

/// VoiceQueryModelCollectionConfig : Configuration for the voice query model
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VoiceQueryModelCollectionConfig<'a> {
    #[serde(rename = "model_name", skip_serializing_if = "Option::is_none")]
    pub model_name: Option<Cow<'a, str>>,
    #[serde(skip)]
    pub _phantom: PhantomData<&'a ()>,
}

impl<'a> VoiceQueryModelCollectionConfig<'a> {
    /// Configuration for the voice query model
    pub fn new() -> Self {
        Self {
            model_name: None,
            _phantom: PhantomData,
        }
    }
}
