/*
 * Typesense API
 *
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VoiceQueryModelCollectionConfig : Configuration for the voice query model 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize, bon::Builder)]
#[builder(on(String, into))]
pub struct VoiceQueryModelCollectionConfig {
    #[serde(rename = "model_name", skip_serializing_if = "Option::is_none")]
    pub model_name: Option<String>,
}

impl VoiceQueryModelCollectionConfig {
    /// Configuration for the voice query model 
    pub fn new() -> VoiceQueryModelCollectionConfig{
        VoiceQueryModelCollectionConfig {
            model_name: None,
        }
    }
}

