//! # Typesense generic models
mod multi_search;
mod scoped_key_parameters;
mod search_result;
pub use multi_search::*;
pub use scoped_key_parameters::*;
pub use search_result::*;

pub use typesense_codegen::models::{
    AnalyticsEventCreateResponse, AnalyticsEventCreateSchema, AnalyticsRuleDeleteResponse,
    AnalyticsRuleParameters, AnalyticsRuleParametersDestination, AnalyticsRuleParametersSource,
    AnalyticsRuleParametersSourceEventsInner, AnalyticsRuleSchema, AnalyticsRuleUpsertSchema,
    AnalyticsRulesRetrieveSchema, ApiKey, ApiKeyDeleteResponse, ApiKeySchema, ApiKeysResponse,
    ApiResponse, ApiStatsResponse, CollectionAlias, CollectionAliasSchema,
    CollectionAliasesResponse, CollectionResponse, CollectionSchema, CollectionUpdateSchema,
    ConversationModelCreateSchema, ConversationModelSchema, ConversationModelUpdateSchema,
    Debug200Response, DeleteDocuments200Response, DeleteDocumentsParameters,
    DeleteStopwordsSet200Response, DirtyValues, DocumentIndexParameters, DropTokensMode,
    ErrorResponse, ExportDocumentsParameters, FacetCounts, FacetCountsCountsInner,
    FacetCountsStats, Field, FieldEmbed, FieldEmbedModelConfig, HealthStatus,
    ImportDocumentsParameters, IndexAction, ListStemmingDictionaries200Response,
    MultiSearchCollectionParameters, MultiSearchParameters, MultiSearchResult,
    MultiSearchResultItem, NlSearchModelBase, NlSearchModelCreateSchema, NlSearchModelDeleteSchema,
    NlSearchModelSchema, PresetDeleteSchema, PresetSchema, PresetUpsertSchema,
    PresetUpsertSchemaValue, PresetsRetrieveSchema, SchemaChangeStatus, SearchGroupedHit,
    SearchHighlight, SearchOverride, SearchOverrideDeleteResponse, SearchOverrideExclude,
    SearchOverrideInclude, SearchOverrideRule, SearchOverrideSchema, SearchOverridesResponse,
    SearchParameters, SearchResultConversation, SearchResultHitTextMatchInfo,
    SearchResultRequestParams, SearchResultRequestParamsVoiceQuery, SearchSynonym,
    SearchSynonymDeleteResponse, SearchSynonymSchema, SearchSynonymsResponse, SnapshotParameters,
    StemmingDictionary, StemmingDictionaryWordsInner, StopwordsSetRetrieveSchema,
    StopwordsSetSchema, StopwordsSetUpsertSchema, StopwordsSetsRetrieveAllSchema, SuccessStatus,
    UpdateDocuments200Response, UpdateDocumentsParameters, VoiceQueryModelCollectionConfig,
};
// Only re-export the sub modules that have enums inside them.
pub use typesense_codegen::models::{
    analytics_rule_schema::Type as AnalyticsRulesType, // analytics_rule_upsert_schema,
    api_key,
    api_key_delete_response,
    api_key_schema,
    api_keys_response,
    api_response,
    api_stats_response,
    collection_alias,
    collection_alias_schema,
    collection_aliases_response,
    collection_response,
    collection_schema,
    collection_update_schema,
    conversation_model_create_schema,
    conversation_model_schema,
    conversation_model_update_schema,
    debug_200_response,
    delete_documents_200_response,
    delete_documents_parameters,
    delete_stopwords_set_200_response,
    document_index_parameters,
    drop_tokens_mode,
    error_response,
    export_documents_parameters,
    facet_counts,
    facet_counts_counts_inner,
    facet_counts_stats,
    field,
    field_embed,
    field_embed_model_config,
    health_status,
    import_documents_parameters,
    index_action,
    list_stemming_dictionaries_200_response,
    multi_search_collection_parameters,
    multi_search_parameters,
    multi_search_result,
    multi_search_result_item,
    multi_search_searches_parameter,
    nl_search_model_base,
    nl_search_model_create_schema,
    nl_search_model_delete_schema,
    nl_search_model_schema,
    preset_delete_schema,
    preset_schema,
    preset_upsert_schema,
    preset_upsert_schema_value,
    presets_retrieve_schema,
    schema_change_status,
    search_grouped_hit,
    search_highlight,
    search_override,
    search_override_delete_response,
    search_override_exclude,
    search_override_include,
    search_override_rule,
    search_override_schema,
    search_overrides_response,
    search_parameters,
    search_result_conversation,
    search_result_hit_text_match_info,
    search_result_request_params,
    search_result_request_params_voice_query,
    search_synonym,
    search_synonym_delete_response,
    search_synonym_schema,
    search_synonyms_response,
    snapshot_parameters,
    stemming_dictionary,
    stemming_dictionary_words_inner,
    stopwords_set_retrieve_schema,
    stopwords_set_schema,
    stopwords_set_upsert_schema,
    stopwords_sets_retrieve_all_schema,
    success_status,
    update_documents_200_response,
    update_documents_parameters,
};
